In [44]:
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
lr = 0.1

In [27]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [28]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [42]:
weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1

In [46]:
for iter in range(10000):
    output0 = x
    output = sig(np.dot(output0,weights) + bias)
    first_term = output - y
    input_for_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term*second_term
    first_two.shape
    changes = np.dot(output0.T,first_two)
    weights = weights - lr*changes
    bias_change = np.sum(first_two)
    bias = bias - lr*bias_change
output = sig(np.dot(x,weights) + bias)
weights,bias,output

(array([[6.32524378],
        [6.32524378]]),
 array([-9.57753185]),
 array([[6.92629022e-05],
        [3.72447556e-02],
        [3.72447556e-02],
        [9.55763307e-01]]))

In [35]:
second_term

array([[0.23480288],
       [0.24844495],
       [0.1885251 ],
       [0.23898623]])