In [7]:
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T

In [8]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [9]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [10]:
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [19]:
for iter in range(10000):
    output0 = x
    inputHidden = np.dot(output0,wh) + bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo) + bo
    output = sig(inputForOutputLayer)

    first_term_output_layer = output - y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer,axis = 0,keepdims = True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims = True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias

    output0 = x
    inputHidden = np.dot(output0,wh) + bh
    outputHidden = sig(np.dot(output0,wh) + bh)
    inputForOutputLayer = np.dot(outputHidden,wo) + bo
    output = sig(inputForOutputLayer)
output,wh,bh,wo,bo

(array([[0.00352404],
        [0.01540269],
        [0.0152665 ],
        [0.97421211]]),
 array([[-0.2677309 , -4.34183115],
        [ 0.11243912, -4.32708165]]),
 array([[-0.61307602,  6.06002662]]),
 array([[ 0.33108901],
        [-9.99649915]]),
 array([[4.21227155]]))